version: '3'
services:
    angular-app:
        environment:
            - CHOKIDAR_USEPOLLING=true
        build: 
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - '8080:80'
        volumes:
            - /usr/app/node_modules
            - .:/usr/app
